ARG BASE_OS=${BASE_OS:-"BASE_OS NOT SET"}
ARG DOCKER_PYTHON_VERSION=${DOCKER_PYTHON_VERSION:-"DOCKER_PYTHON_VERSION NOT SET"}
ARG PYTHON_VERSION=${PYTHON_VERSION:-"PYTHON_VERSION NOT SET"}
ARG DEVBOX_RELEASE_DATE=${DEVBOX_RELEASE_DATE:-"SERVICE_RELEASE_DATE NOT SET"}

FROM wayfair/python/${BASE_OS}-${DOCKER_PYTHON_VERSION}-devbox:${PYTHON_VERSION}-${DEVBOX_RELEASE_DATE}

USER root

RUN yum -y install  snappy lz4
