#!/usr/bin/env bash

pip freeze | xargs pip uninstall -y
pip install -r requirements.txt
printf "# THIS IS AN AUTOGENERATED LOCKFILE. DO NOT EDIT MANUALLY.\n" > requirements.lock
pip freeze --disable-pip-version-check >> requirements.lock